title: Arie's blog
description: >
  My programming blog where I write about Python, functional programming,
  and API design.
baseurl: "/"
url: "https://ariebovenberg.github.io"

# Theme
author:
  name: Arie Bovenberg
  email: arie@bovenberg.net
show_excerpts: true
minima:
  # skin: dark
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    github:  ariebovenberg
    linkedin: ariebovenberg
    # devto: ariebovenberg
    # twitter: ariebovenberg

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

google_analytics: "297234170"
permalink: /:title/
markdown: kramdown
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

disqus:
  shortname: my_disqus_shortname

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE
  - README.md
