title: Arie Bovenberg
description: ""
baseurl: ""
url: "https://dev.arie.bovenberg.net"

# author:
#   name: Arie Bovenberg
#   email: null
show_excerpts: true
minima:
  skin: arie-autodark
  date_format: "%b %-d, %Y"
  social_links:
    github:  ariebovenberg
    linkedin: ariebovenberg
    # devto: ariebovenberg
    # twitter: ariebovenberg

header_pages:
  - _pages/home.md
  - _pages/blog.md
  - _pages/about.md

include:
  - _pages

google_analytics: "G-0B2WZJQ5RK"
permalink: blog/:title/
markdown: kramdown
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

# disqus:
#   shortname: ariebovenbergdevblog

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE
  - README.md
  - _code
